before_script: "bundle install && cd spec/dummy_app && bundle install && cd ../.. && bundle exec rake rails_admin:prepare_ci_env db:create db:migrate"
rvm:
  - 1.8.7
  - 1.9.2
  - rbx
  - ree
  - ruby-head
env:
  - "CI_DB_ADAPTER=sqlite3"
  - "CI_DB_ADAPTER=postgresql"
  - "CI_DB_ADAPTER=mysql"
notifications:
  irc: "irc.freenode.org#railsadmin"
