bundler_args: "--without debug"
rvm:
  - jruby-18mode
  - 1.8.7
  - 1.9.3
env:
  - "CI_ORM=active_record CI_DB_ADAPTER=sqlite3"
  - "CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres"
  - "CI_ORM=active_record CI_DB_ADAPTER=mysql"
  - "CI_ORM=mongoid"
  - "CI_ORM=mongoid CI_ORM_VERSION=head"
language: ruby
notifications:
  irc: "irc.freenode.org#railsadmin"
script: spec/ci.sh
